"""Canned RecommendationResponse fixtures used when TEST_MODE is enabled.

Built from Pydantic models so any schema drift fails at backend import,
not at request time. Add new variants here as the UX grows.
"""
from models import (
    Coords,
    Critic,
    DrinkWindow,
    RecommendationResponse,
    StructureBars,
    WineColor,
    WineRecommendation,
)

_BRUNELLO_COLOR = WineColor(glass='#7d1f24', tint='#f4dcd3', ink='#3a0d10', accent='#9a2a30')
_BAROLO_COLOR   = WineColor(glass='#8a2a2e', tint='#f3dad4', ink='#3d1014', accent='#a83339')
_CHABLIS_COLOR  = WineColor(glass='#d9b743', tint='#f5ecc8', ink='#5a4612', accent='#b89826')
_RHONE_COLOR    = WineColor(glass='#7d1f24', tint='#f4dcd3', ink='#3a0d10', accent='#9a2a30')

_HAPPY = RecommendationResponse(
    recommendations=[
        WineRecommendation(
            rank=1,
            wine_name="Brunello di Montalcino",
            producer="Biondi-Santi",
            vintage=2016,
            region="Tuscany, Italy",
            price=185.0,
            reasoning="Closely mirrors the structured Sangiovese profile your cellar leans on, with the savoury earth and dried-cherry character you consistently rate highly. The 2016 vintage is drinking in its primary fruit window, matching the meal's richness without overshadowing it.",
            confidence="high — strong style overlap with cellar favourites",
            fits=["structured tannin", "savoury earth", "dried cherry"],
            appellation="Brunello di Montalcino DOCG",
            country="Italy",
            coords=Coords(lat=43.05, lon=11.49),
            grape="Sangiovese Grosso",
            abv=14.5,
            drink=DrinkWindow(from_year=2022, peak=2032, until=2042),
            color=_BRUNELLO_COLOR,
            bars=StructureBars(tannin=9.0, acidity=7.5, body=8.0, sweetness=1.0, oak=4.0),
            wheel={"Dried Cherry": 9, "Leather": 6, "Tobacco": 5, "Earth": 8, "Violet": 5, "Plum": 5, "Anise": 4, "Forest Floor": 6},
            nose="Dried cherry, violet and iron dust with a note of forest floor.",
            palate="Full-bodied with firm, grippy tannins, bright acidity and a long savoury finish.",
            pairs=["Bistecca alla Fiorentina", "Aged pecorino", "Wild boar ragù"],
            critic=Critic(score=96, source="Wine Spectator"),
        ),
        WineRecommendation(
            rank=2,
            wine_name="Barolo Cannubi",
            producer="Marchesi di Barolo",
            vintage=2018,
            region="Piedmont, Italy",
            price=145.0,
            reasoning="Nebbiolo's rose-and-tar aromatics line up with the floral red wines you've previously enjoyed. Slightly younger and more grippy than the Brunello, so it benefits from a decant before service.",
            confidence="high — varietal and producer both align with profile",
            fits=["floral nebbiolo", "firm tannin", "age-worthy"],
            appellation="Barolo DOCG",
            country="Italy",
            coords=Coords(lat=44.61, lon=7.94),
            grape="Nebbiolo",
            abv=14.0,
            drink=DrinkWindow(from_year=2024, peak=2033, until=2045),
            color=_BAROLO_COLOR,
            bars=StructureBars(tannin=9.5, acidity=8.0, body=7.5, sweetness=1.0, oak=5.0),
            wheel={"Rose Petal": 8, "Tar": 7, "Sour Cherry": 7, "Truffle": 5, "Star Anise": 4, "Raspberry": 5, "Dried Herb": 6, "Iron": 4},
            nose="Rose petal and tar with sour cherry and a wisp of dried herb.",
            palate="Taut and structured, with high acidity, gripping tannins and a long mineral finish.",
            pairs=["Brasato al Barolo", "White truffle risotto", "Aged comté"],
            critic=Critic(score=94, source="Wine Advocate"),
        ),
        WineRecommendation(
            rank=3,
            wine_name="Chianti Classico Riserva",
            producer="Felsina",
            vintage=2019,
            region="Tuscany, Italy",
            price=72.0,
            reasoning="The value pick — Felsina's Riserva delivers a lot of the Brunello's character at less than half the price. A safe pour if the table wants something approachable without trading away the savoury Tuscan profile.",
            confidence="medium — good fit, lower stylistic complexity",
            fits=["value", "approachable", "tuscan classic"],
            appellation="Chianti Classico Riserva DOCG",
            country="Italy",
            coords=Coords(lat=43.42, lon=11.27),
            grape="Sangiovese",
            abv=13.5,
            drink=DrinkWindow(from_year=2022, peak=2028, until=2034),
            color=_BRUNELLO_COLOR,
            bars=StructureBars(tannin=7.5, acidity=7.0, body=7.0, sweetness=1.0, oak=4.5),
            wheel={"Dried Cherry": 8, "Leather": 5, "Tobacco": 4, "Earth": 7, "Violet": 4, "Plum": 6, "Herb": 5, "Cedar": 3},
            nose="Dried cherry and leather with earthy undertones and a hint of cedar.",
            palate="Medium-full body, firm but approachable tannins and a clean savoury finish.",
            pairs=["Grilled bistecca", "Sheep's milk ricotta", "Mushroom pasta"],
            critic=Critic(score=91, source="Gambero Rosso"),
        ),
    ],
    list_quality_note=None,
    profile_match_summary="The list leans heavily Italian, which plays directly to your cellar's Sangiovese and Nebbiolo bias. Three strong matches were easy to find.",
)

_SPARSE = RecommendationResponse(
    recommendations=[
        WineRecommendation(
            rank=1,
            wine_name="House Red",
            producer=None,
            vintage=None,
            region=None,
            price=None,
            reasoning="Listed simply as 'house red' with no producer or vintage on the menu. Style cues suggest medium-bodied Mediterranean blend, which aligns roughly with your preferences.",
            confidence="medium — limited list metadata",
            fits=None,
            appellation=None,
            country=None,
            coords=None,
            grape=None,
            abv=None,
            drink=None,
            color=_RHONE_COLOR,
            bars=StructureBars(tannin=6.0, acidity=6.0, body=6.0, sweetness=2.0, oak=4.0),
            wheel={"Red Fruit": 7, "Earth": 6, "Spice": 5, "Oak": 4, "Herb": 5, "Dark Fruit": 5, "Floral": 3, "Mineral": 4},
            nose="Generic red-fruit and dried herb nose with moderate oak.",
            palate="Medium body and tannin with a clean, straightforward finish.",
            pairs=["Grilled meats", "Hard cheese", "Pasta al ragù"],
            critic=None,
        ),
        WineRecommendation(
            rank=2,
            wine_name="Rioja Reserva",
            producer="Unspecified",
            vintage=None,
            region="Rioja",
            price=None,
            reasoning="No vintage or producer listed, but Rioja Reserva designation guarantees minimum aging that should deliver the savoury, leather-edged style your profile gravitates to.",
            confidence="medium — designation-only inference",
            fits=["savoury", "aged"],
            appellation="Rioja Reserva DOC",
            country="Spain",
            coords=Coords(lat=42.47, lon=-2.45),
            grape="Tempranillo",
            abv=13.5,
            drink=None,
            color=_BRUNELLO_COLOR,
            bars=StructureBars(tannin=7.0, acidity=6.5, body=7.0, sweetness=1.5, oak=6.0),
            wheel={"Dried Cherry": 7, "Vanilla": 6, "Cedar": 5, "Leather": 6, "Tobacco": 5, "Plum": 6, "Herb": 4, "Earth": 5},
            nose="Vanilla and cedar oak with dried cherry and subtle leather.",
            palate="Medium-full body with smooth, integrated tannins and a spiced finish.",
            pairs=["Lamb chops", "Manchego cheese", "Chorizo"],
            critic=None,
        ),
        WineRecommendation(
            rank=3,
            wine_name="Pinot Noir",
            producer=None,
            vintage=2021,
            region=None,
            price=58.0,
            reasoning="Only varietal and vintage given. Defensible pick at this price point if the table wants lighter-bodied red.",
            confidence="low — varietal-only match",
            fits=[],
            appellation=None,
            country=None,
            coords=None,
            grape="Pinot Noir",
            abv=13.0,
            drink=DrinkWindow(from_year=2022, peak=2026, until=2029),
            color=_BRUNELLO_COLOR,
            bars=StructureBars(tannin=4.0, acidity=7.0, body=5.0, sweetness=2.0, oak=3.5),
            wheel={"Red Cherry": 8, "Raspberry": 7, "Rose": 5, "Earth": 5, "Mushroom": 4, "Vanilla": 4, "Clove": 3, "Smoke": 3},
            nose="Red cherry and raspberry with a floral lift and earthy undertone.",
            palate="Light-medium body, silky tannins and a fresh, fruit-forward finish.",
            pairs=["Duck breast", "Salmon", "Mushroom risotto"],
            critic=None,
        ),
    ],
    list_quality_note="List has minimal producer and vintage information — confidence is capped accordingly.",
    profile_match_summary="Sparse list metadata limited how precisely the cellar profile could be matched.",
)

_LONG_REASONING = RecommendationResponse(
    recommendations=[
        WineRecommendation(
            rank=1,
            wine_name="Châteauneuf-du-Pape",
            producer="Domaine du Vieux Télégraphe",
            vintage=2017,
            region="Rhône, France",
            price=165.0,
            reasoning=(
                "This is one of the most consistent matches available on the list relative to your cellar. "
                "Vieux Télégraphe's house style — Grenache-led but with meaningful Mourvèdre and Syrah backbone — "
                "produces the kind of warm-fruited but savoury, garrigue-tinged red you've rated 90+ on across "
                "five separate occasions in your tasting history. The 2017 vintage is a touch riper than the classic "
                "norm, which actually plays well with the meal's richness without becoming jammy."
            ),
            confidence="high — five separate profile matches in tasting history",
            fits=["grenache-led southern rhône", "garrigue", "savoury warmth"],
            appellation="Châteauneuf-du-Pape AOC",
            country="France",
            coords=Coords(lat=44.06, lon=4.83),
            grape="Grenache (dominant), Mourvèdre, Syrah",
            abv=15.0,
            drink=DrinkWindow(from_year=2022, peak=2029, until=2038),
            color=_RHONE_COLOR,
            bars=StructureBars(tannin=7.0, acidity=5.5, body=9.0, sweetness=2.0, oak=3.0),
            wheel={"Red Berry": 8, "Garrigue": 9, "Leather": 6, "Spice": 7, "Dried Fig": 7, "Tobacco": 5, "Olive": 4, "Iron": 3},
            nose="Sun-baked garrigue, red berry and dried fig with a leathery mineral edge.",
            palate="Full and voluptuous with soft tannins, low acidity and a long spiced finish.",
            pairs=["Roasted lamb", "Tapenade crostini", "Wild mushroom gratin"],
            critic=Critic(score=95, source="Wine Advocate"),
        ),
        WineRecommendation(
            rank=2,
            wine_name="Côte-Rôtie",
            producer="E. Guigal",
            vintage=2018,
            region="Northern Rhône, France",
            price=210.0,
            reasoning=(
                "Northern Rhône Syrah brings the bacon-fat and black-pepper aromatics that your CellarTracker notes "
                "single out repeatedly. Guigal's brand-tier Côte-Rôtie isn't the most exciting expression of the appellation "
                "but it is structurally faithful, and 2018 was a strong vintage. The step up in price relative to the "
                "Châteauneuf is real, so this becomes the right pick only if the table is happy with the spend."
            ),
            confidence="high — northern Rhône Syrah is a known sweet spot",
            fits=["bacon fat", "black pepper", "structured syrah"],
            appellation="Côte-Rôtie AOC",
            country="France",
            coords=Coords(lat=45.47, lon=4.79),
            grape="Syrah (with Viognier co-fermentation)",
            abv=13.5,
            drink=DrinkWindow(from_year=2024, peak=2033, until=2043),
            color=_RHONE_COLOR,
            bars=StructureBars(tannin=8.0, acidity=7.0, body=8.0, sweetness=1.0, oak=5.5),
            wheel={"Blackberry": 8, "Bacon Fat": 9, "Black Pepper": 8, "Violet": 7, "Olive": 5, "Graphite": 5, "Smoked Meat": 6, "Iron": 4},
            nose="Bacon fat, violet and blackberry with cracked black pepper and a mineral finish.",
            palate="Structured and linear with firm tannins, high acidity and a long peppery close.",
            pairs=["Lamb with black olive tapenade", "Duck confit", "Truffle-butter steak"],
            critic=Critic(score=93, source="Wine Spectator"),
        ),
        WineRecommendation(
            rank=3,
            wine_name="Bandol Rouge",
            producer="Domaine Tempier",
            vintage=2019,
            region="Provence, France",
            price=125.0,
            reasoning=(
                "Tempier is a less obvious but high-upside match — Mourvèdre-dominant Bandol has the wild herb and "
                "iron-edged savoury character that overlaps with your Italian and Southern Rhône preferences. "
                "If you want to try something at the edge of your usual palette without leaving the safety zone, "
                "this is the one. The 2019 is still tight; ask the somm if they'll decant it for 30+ minutes."
            ),
            confidence="medium — adjacent style, less direct history",
            fits=["mourvèdre-led", "wild herb", "savoury iron"],
            appellation="Bandol AOC",
            country="France",
            coords=Coords(lat=43.14, lon=5.75),
            grape="Mourvèdre (dominant), Grenache, Cinsault",
            abv=13.5,
            drink=DrinkWindow(from_year=2025, peak=2032, until=2040),
            color=_RHONE_COLOR,
            bars=StructureBars(tannin=8.5, acidity=6.5, body=8.0, sweetness=1.0, oak=3.5),
            wheel={"Wild Herb": 9, "Blackberry": 7, "Iron": 7, "Smoke": 6, "Leather": 6, "Pepper": 5, "Dark Plum": 6, "Garrigue": 7},
            nose="Wild herb, blackberry and iron with smoky garrigue and cracked pepper.",
            palate="Firm and tannic with a savoury iron-edged character and a very long finish.",
            pairs=["Grilled lamb with herbes de Provence", "Bouillabaisse", "Hard goat cheese"],
            critic=Critic(score=92, source="Jancis Robinson"),
        ),
    ],
    list_quality_note=None,
    profile_match_summary=(
        "The list is unusually deep in French Rhône and Provençal reds, which maps almost directly onto the savoury, "
        "structured, herb-inflected reds that dominate your cellar. Three strong picks were identified without needing "
        "to reach into adjacent styles, and a fourth (Cornas) is worth asking about if these are unavailable. Overall, "
        "this is one of the better profile-fit scenarios across recent uploads."
    ),
)

_LOW_CONFIDENCE = RecommendationResponse(
    recommendations=[
        WineRecommendation(
            rank=1,
            wine_name="Cabernet Sauvignon",
            producer="Generic Napa",
            vintage=2020,
            region="Napa Valley",
            price=95.0,
            reasoning="Best-effort match on a list that's almost entirely outside your usual style. New World Cab is not a cellar strength but it's the most structurally credible option here.",
            confidence="low — list does not overlap with profile",
            fits=["fallback", "structured", "new world"],
            appellation="Napa Valley AVA",
            country="USA",
            coords=Coords(lat=38.5, lon=-122.4),
            grape="Cabernet Sauvignon",
            abv=14.5,
            drink=DrinkWindow(from_year=2023, peak=2028, until=2035),
            color=_BRUNELLO_COLOR,
            bars=StructureBars(tannin=8.0, acidity=5.5, body=9.0, sweetness=2.0, oak=8.0),
            wheel={"Blackcurrant": 9, "Cedar": 7, "Dark Plum": 7, "Vanilla": 7, "Tobacco": 5, "Mint": 4, "Graphite": 4, "Mocha": 5},
            nose="Blackcurrant and dark plum with heavy vanilla oak, cedar and a mint accent.",
            palate="Full-bodied and plush with ripe tannins, prominent oak and a jammy fruit finish.",
            pairs=["Prime rib", "Aged cheddar", "Dark chocolate"],
            critic=Critic(score=88, source="Wine Enthusiast"),
        ),
        WineRecommendation(
            rank=2,
            wine_name="Chardonnay",
            producer="Sonoma Coast",
            vintage=2021,
            region="Sonoma",
            price=68.0,
            reasoning="If a white is preferred, this is the closest the list comes to the lees-y, mineral whites you've previously enjoyed.",
            confidence="low — style adjacency only",
            fits=["lees-y", "mineral-adjacent"],
            appellation="Sonoma Coast AVA",
            country="USA",
            coords=Coords(lat=38.4, lon=-122.9),
            grape="Chardonnay",
            abv=13.5,
            drink=DrinkWindow(from_year=2022, peak=2026, until=2029),
            color=_CHABLIS_COLOR,
            bars=StructureBars(tannin=1.0, acidity=7.5, body=7.0, sweetness=1.5, oak=5.5),
            wheel={"Lemon Zest": 7, "Green Apple": 6, "Cream": 6, "Toasty Oak": 5, "Butter": 5, "Mineral": 5, "Pear": 6, "Hazelnut": 4},
            nose="Lemon zest and green apple with a creamy lees note and toasty oak.",
            palate="Medium-full body with moderate acidity, a buttery texture and warm finish.",
            pairs=["Lobster bisque", "Roast chicken", "Comté cheese"],
            critic=Critic(score=87, source="Wine Advocate"),
        ),
        WineRecommendation(
            rank=3,
            wine_name="Merlot",
            producer="Unspecified",
            vintage=2019,
            region="California",
            price=52.0,
            reasoning="Included only to fill the third slot — generic California Merlot does not meaningfully match your profile.",
            confidence="low — third-slot filler",
            fits=[],
            appellation=None,
            country="USA",
            coords=Coords(lat=36.7, lon=-119.4),
            grape="Merlot",
            abv=13.5,
            drink=DrinkWindow(from_year=2021, peak=2025, until=2028),
            color=_BRUNELLO_COLOR,
            bars=StructureBars(tannin=5.5, acidity=5.0, body=7.0, sweetness=3.0, oak=5.0),
            wheel={"Plum": 8, "Chocolate": 6, "Cherry": 7, "Cedar": 4, "Herb": 3, "Vanilla": 5, "Mocha": 4, "Cassis": 5},
            nose="Plum and milk chocolate with cherry, soft herb and vanilla.",
            palate="Medium body and soft tannins — approachable but lacking complexity.",
            pairs=["Pasta bolognese", "Mild cheddar", "Roasted vegetables"],
            critic=None,
        ),
    ],
    list_quality_note="This list skews heavily toward New World styles that don't overlap with the cellar. Consider asking the restaurant if a reserve or off-menu list is available.",
    profile_match_summary="Poor overall fit between the list and your profile — all three picks are low-confidence by design.",
)

_TWO_WINES = RecommendationResponse(
    recommendations=[
        WineRecommendation(
            rank=1,
            wine_name="Riesling Spätlese",
            producer="J.J. Prüm",
            vintage=2019,
            region="Mosel, Germany",
            price=88.0,
            reasoning="Direct hit on the off-dry German Riesling style that dominates your white-wine tasting history. Prüm's Spätlese is age-worthy and a clear top pick.",
            confidence="high — strongest match on the list",
            fits=["off-dry", "mosel slate", "age-worthy"],
            appellation="Mosel QmP Spätlese",
            country="Germany",
            coords=Coords(lat=49.92, lon=7.06),
            grape="Riesling",
            abv=8.0,
            drink=DrinkWindow(from_year=2023, peak=2032, until=2044),
            color=_CHABLIS_COLOR,
            bars=StructureBars(tannin=0.5, acidity=9.5, body=4.0, sweetness=5.0, oak=0.5),
            wheel={"Lime Zest": 9, "Slate": 9, "Green Apple": 7, "Petrol": 5, "Apricot": 6, "White Flower": 7, "Peach": 6, "Honey": 4},
            nose="Lime zest and slate minerality with white flower, apricot and a faint petrol note.",
            palate="Off-dry with razor acidity cutting through the residual sweetness — long and electric.",
            pairs=["Plateau de fruits de mer", "Asian-spiced duck", "Blue cheese"],
            critic=Critic(score=95, source="Wine Advocate"),
        ),
        WineRecommendation(
            rank=2,
            wine_name="Grüner Veltliner Smaragd",
            producer="Hirtzberger",
            vintage=2020,
            region="Wachau, Austria",
            price=92.0,
            reasoning="A second viable option if a drier white is preferred. Smaragd-level Grüner has the texture and white-pepper bite that overlap meaningfully with your profile.",
            confidence="medium — adjacent style to your sweet spot",
            fits=["dry", "white pepper", "textured"],
            appellation="Wachau Smaragd",
            country="Austria",
            coords=Coords(lat=48.38, lon=15.43),
            grape="Grüner Veltliner",
            abv=13.5,
            drink=DrinkWindow(from_year=2022, peak=2028, until=2034),
            color=_CHABLIS_COLOR,
            bars=StructureBars(tannin=0.5, acidity=8.5, body=7.0, sweetness=1.0, oak=1.0),
            wheel={"White Pepper": 9, "Lemon Zest": 8, "Green Herb": 6, "Mineral": 8, "Grapefruit": 6, "Stone Fruit": 5, "Smoke": 3, "Flint": 5},
            nose="White pepper, lemon zest and mineral smoke with a herbal and stone-fruit edge.",
            palate="Full-bodied and dry with searing acidity, a peppery spine and a mineral close.",
            pairs=["Wiener Schnitzel", "Asparagus and hollandaise", "Smoked trout"],
            critic=Critic(score=92, source="Wine Spectator"),
        ),
    ],
    list_quality_note="Only two wines on the list cleanly matched the profile — included a second pick instead of stretching to a weak third.",
    profile_match_summary="Narrow but strong overlap on Germanic whites; the rest of the list is outside the cellar's character.",
)

FIXTURES: dict[str, RecommendationResponse] = {
    "happy": _HAPPY,
    "sparse": _SPARSE,
    "long_reasoning": _LONG_REASONING,
    "low_confidence": _LOW_CONFIDENCE,
    "two_wines": _TWO_WINES,
}
