// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CacheStatsDebugCacheStatsGetData, CacheStatsDebugCacheStatsGetResponses, ClearCacheDebugCacheClearPostData, ClearCacheDebugCacheClearPostResponses, GetConfigDebugConfigGetData, GetConfigDebugConfigGetResponses, GetInventoryInventoryGetData, GetInventoryInventoryGetResponses, GetRecentLogsDebugLogsRecentGetData, GetRecentLogsDebugLogsRecentGetErrors, GetRecentLogsDebugLogsRecentGetResponses, GetVersionDebugVersionGetData, GetVersionDebugVersionGetResponses, HealthCheckDebugHealthGetData, HealthCheckDebugHealthGetResponses, ListEndpointsDebugEndpointsGetData, ListEndpointsDebugEndpointsGetResponses, MemoryUsageDebugMemoryGetData, MemoryUsageDebugMemoryGetResponses, PingDebugPingGetData, PingDebugPingGetResponses, ProfileSummaryProfileSummaryGetData, ProfileSummaryProfileSummaryGetResponses, RecommendRecommendPostData, RecommendRecommendPostErrors, RecommendRecommendPostResponses, StatusOverviewDebugStatusGetData, StatusOverviewDebugStatusGetResponses, UploadInventoryUploadInventoryPostData, UploadInventoryUploadInventoryPostErrors, UploadInventoryUploadInventoryPostResponses, UploadProfileUploadProfilePostData, UploadProfileUploadProfilePostErrors, UploadProfileUploadProfilePostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * Basic health check endpoint.
 */
export const healthCheckDebugHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckDebugHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckDebugHealthGetResponses, unknown, ThrowOnError>({ url: '/debug/health', ...options });

/**
 * Status Overview
 *
 * Comprehensive status overview including system and service metrics.
 */
export const statusOverviewDebugStatusGet = <ThrowOnError extends boolean = false>(options?: Options<StatusOverviewDebugStatusGetData, ThrowOnError>) => (options?.client ?? client).get<StatusOverviewDebugStatusGetResponses, unknown, ThrowOnError>({ url: '/debug/status', ...options });

/**
 * Cache Stats
 *
 * Get cache statistics.
 */
export const cacheStatsDebugCacheStatsGet = <ThrowOnError extends boolean = false>(options?: Options<CacheStatsDebugCacheStatsGetData, ThrowOnError>) => (options?.client ?? client).get<CacheStatsDebugCacheStatsGetResponses, unknown, ThrowOnError>({ url: '/debug/cache/stats', ...options });

/**
 * Clear Cache
 *
 * Clear all cached responses.
 */
export const clearCacheDebugCacheClearPost = <ThrowOnError extends boolean = false>(options?: Options<ClearCacheDebugCacheClearPostData, ThrowOnError>) => (options?.client ?? client).post<ClearCacheDebugCacheClearPostResponses, unknown, ThrowOnError>({ url: '/debug/cache/clear', ...options });

/**
 * Get Config
 *
 * Get current configuration.
 */
export const getConfigDebugConfigGet = <ThrowOnError extends boolean = false>(options?: Options<GetConfigDebugConfigGetData, ThrowOnError>) => (options?.client ?? client).get<GetConfigDebugConfigGetResponses, unknown, ThrowOnError>({ url: '/debug/config', ...options });

/**
 * Get Recent Logs
 *
 * Get recent log entries (last N lines).
 */
export const getRecentLogsDebugLogsRecentGet = <ThrowOnError extends boolean = false>(options?: Options<GetRecentLogsDebugLogsRecentGetData, ThrowOnError>) => (options?.client ?? client).get<GetRecentLogsDebugLogsRecentGetResponses, GetRecentLogsDebugLogsRecentGetErrors, ThrowOnError>({ url: '/debug/logs/recent', ...options });

/**
 * List Endpoints
 *
 * List all available API endpoints.
 */
export const listEndpointsDebugEndpointsGet = <ThrowOnError extends boolean = false>(options?: Options<ListEndpointsDebugEndpointsGetData, ThrowOnError>) => (options?.client ?? client).get<ListEndpointsDebugEndpointsGetResponses, unknown, ThrowOnError>({ url: '/debug/endpoints', ...options });

/**
 * Memory Usage
 *
 * Get memory usage information.
 */
export const memoryUsageDebugMemoryGet = <ThrowOnError extends boolean = false>(options?: Options<MemoryUsageDebugMemoryGetData, ThrowOnError>) => (options?.client ?? client).get<MemoryUsageDebugMemoryGetResponses, unknown, ThrowOnError>({ url: '/debug/memory', ...options });

/**
 * Ping
 *
 * Simple ping endpoint for connectivity testing.
 */
export const pingDebugPingGet = <ThrowOnError extends boolean = false>(options?: Options<PingDebugPingGetData, ThrowOnError>) => (options?.client ?? client).get<PingDebugPingGetResponses, unknown, ThrowOnError>({ url: '/debug/ping', ...options });

/**
 * Get Version
 *
 * Get API version information.
 */
export const getVersionDebugVersionGet = <ThrowOnError extends boolean = false>(options?: Options<GetVersionDebugVersionGetData, ThrowOnError>) => (options?.client ?? client).get<GetVersionDebugVersionGetResponses, unknown, ThrowOnError>({ url: '/debug/version', ...options });

/**
 * Upload Inventory
 */
export const uploadInventoryUploadInventoryPost = <ThrowOnError extends boolean = false>(options: Options<UploadInventoryUploadInventoryPostData, ThrowOnError>) => (options.client ?? client).post<UploadInventoryUploadInventoryPostResponses, UploadInventoryUploadInventoryPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/upload-inventory',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Upload Profile
 */
export const uploadProfileUploadProfilePost = <ThrowOnError extends boolean = false>(options: Options<UploadProfileUploadProfilePostData, ThrowOnError>) => (options.client ?? client).post<UploadProfileUploadProfilePostResponses, UploadProfileUploadProfilePostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/upload-profile',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get Inventory
 */
export const getInventoryInventoryGet = <ThrowOnError extends boolean = false>(options?: Options<GetInventoryInventoryGetData, ThrowOnError>) => (options?.client ?? client).get<GetInventoryInventoryGetResponses, unknown, ThrowOnError>({ url: '/inventory', ...options });

/**
 * Profile Summary
 */
export const profileSummaryProfileSummaryGet = <ThrowOnError extends boolean = false>(options?: Options<ProfileSummaryProfileSummaryGetData, ThrowOnError>) => (options?.client ?? client).get<ProfileSummaryProfileSummaryGetResponses, unknown, ThrowOnError>({ url: '/profile-summary', ...options });

/**
 * Recommend
 *
 * Recommend wines based on uploaded list and meal context.
 */
export const recommendRecommendPost = <ThrowOnError extends boolean = false>(options: Options<RecommendRecommendPostData, ThrowOnError>) => (options.client ?? client).post<RecommendRecommendPostResponses, RecommendRecommendPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/recommend',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
