// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AuthMeResponse
 */
export type AuthMeResponse = {
    user: User;
    /**
     * Profiles
     */
    profiles?: Array<Profile>;
};

/**
 * Body_recommend_recommend_post
 */
export type BodyRecommendRecommendPost = {
    /**
     * Meal
     */
    meal?: string;
    /**
     * Style Terms
     */
    style_terms?: string;
    /**
     * Occasion
     */
    occasion?: string;
    /**
     * Menu
     */
    menu?: string;
    /**
     * Cellar Leans
     */
    cellar_leans?: string;
    /**
     * Temperament
     */
    temperament?: string;
    /**
     * Ceiling
     */
    ceiling?: string;
    /**
     * Bottle Count
     */
    bottle_count?: number;
    /**
     * Source Mode
     */
    source_mode?: string;
    /**
     * Wine List
     */
    wine_list?: Blob | File;
    /**
     * Test Fixture
     */
    test_fixture?: string;
};

/**
 * Body_upload_inventory_upload_inventory_post
 */
export type BodyUploadInventoryUploadInventoryPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_profile_upload_profile_post
 */
export type BodyUploadProfileUploadProfilePost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Bottle
 *
 * Model for a wine bottle from CellarTracker
 */
export type Bottle = {
    /**
     * Iwine
     */
    iWine?: string | null;
    /**
     * Type
     */
    type?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Size
     */
    size?: string | null;
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Value
     */
    value?: string | null;
    /**
     * Price
     */
    price?: string | null;
    /**
     * Totalquantity
     */
    totalquantity?: string | null;
    /**
     * Quantity
     */
    quantity?: string | null;
    /**
     * Pending
     */
    pending?: string | null;
    /**
     * Vintage
     */
    vintage?: string | null;
    /**
     * Wine
     */
    wine?: string | null;
    /**
     * Locale
     */
    locale?: string | null;
    /**
     * Producer
     */
    producer?: string | null;
    /**
     * Varietal
     */
    varietal?: string | null;
    /**
     * Mastervarietal
     */
    mastervarietal?: string | null;
    /**
     * Designation
     */
    designation?: string | null;
    /**
     * Vineyard
     */
    vineyard?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Region
     */
    region?: string | null;
    /**
     * Subregion
     */
    subregion?: string | null;
    /**
     * Appellation
     */
    appellation?: string | null;
    /**
     * Beginconsume
     */
    beginconsume?: string | null;
    /**
     * Endconsume
     */
    endconsume?: string | null;
    /**
     * Windowsource
     */
    windowsource?: string | null;
    /**
     * Likevotes
     */
    likevotes?: string | null;
    /**
     * Likepercent
     */
    likepercent?: string | null;
    /**
     * Likeit
     */
    likeit?: string | null;
    /**
     * Pnotes
     */
    pnotes?: string | null;
    /**
     * Pscore
     */
    pscore?: string | null;
    /**
     * Cnotes
     */
    cnotes?: string | null;
    /**
     * Cscore
     */
    cscore?: string | null;
};

/**
 * CellarStats
 *
 * Aggregate statistics computed from the user's cellar inventory.
 */
export type CellarStats = {
    /**
     * Totalbottles
     */
    totalBottles?: number;
    /**
     * Uniquewines
     */
    uniqueWines?: number;
    /**
     * Vintageoldest
     */
    vintageOldest?: number | null;
    /**
     * Vintagenewest
     */
    vintageNewest?: number | null;
};

/**
 * Coords
 */
export type Coords = {
    /**
     * Lat
     */
    lat: number;
    /**
     * Lon
     */
    lon: number;
};

/**
 * Critic
 */
export type Critic = {
    /**
     * Score
     */
    score: number;
    /**
     * Source
     */
    source: string;
};

/**
 * DrinkWindow
 */
export type DrinkWindow = {
    /**
     * From
     */
    from: number;
    /**
     * Peak
     */
    peak: number;
    /**
     * Until
     */
    until: number;
};

/**
 * FlightFeedback
 */
export type FlightFeedback = {
    /**
     * Chip
     */
    chip: string;
    /**
     * Recordedat
     */
    recordedAt: number;
};

/**
 * FlightRecord
 *
 * Full flight record returned by GET /history/{id}.
 */
export type FlightRecord = {
    /**
     * Id
     */
    id: string;
    /**
     * Createdat
     */
    createdAt: number;
    /**
     * Occasion
     */
    occasion: string;
    /**
     * Menu
     */
    menu: string;
    /**
     * Sourcemode
     */
    sourceMode: string;
    /**
     * Bottlecount
     */
    bottleCount: number;
    response: RecommendationResponse;
    feedback?: FlightFeedback | null;
};

/**
 * FlightSummary
 *
 * Lightweight row for GET /history list view.
 */
export type FlightSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Createdat
     */
    createdAt: number;
    /**
     * Occasion
     */
    occasion: string;
    /**
     * Menu
     */
    menu: string;
    /**
     * Topwinename
     */
    topWineName: string;
    /**
     * Bottlecount
     */
    bottleCount: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InventoryResponse
 */
export type InventoryResponse = {
    /**
     * Bottles
     */
    bottles?: Array<Bottle>;
    /**
     * Agehours
     */
    ageHours?: number | null;
    /**
     * Stale
     */
    stale?: boolean;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Profile
 *
 * A named palate profile owned by a user.
 */
export type Profile = {
    /**
     * Id
     */
    id: string;
    /**
     * Userid
     */
    userId?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Isdefault
     */
    isDefault?: boolean;
    /**
     * Createdat
     */
    createdAt: number;
};

/**
 * ProfileCreateRequest
 */
export type ProfileCreateRequest = {
    /**
     * Name
     */
    name: string;
};

/**
 * ProfilePatchRequest
 *
 * Partial edit payload for PATCH /profile.
 *
 * Non-`None` fields are merged into ``profile_data.json["_overrides"]`` and
 * layered on top of the derived profile by ``build_taste_profile()``.
 */
export type ProfilePatchRequest = {
    /**
     * Topvarietals
     */
    topVarietals?: Array<string> | null;
    /**
     * Topregions
     */
    topRegions?: Array<string> | null;
    /**
     * Preferreddescriptors
     */
    preferredDescriptors?: Array<string> | null;
    /**
     * Avoidedstyles
     */
    avoidedStyles?: Array<string> | null;
    /**
     * Avgspend
     */
    avgSpend?: number | null;
    /**
     * Stylesummary
     */
    styleSummary?: string | null;
    tasteMarkers?: TasteMarkers | null;
};

/**
 * ProfileSummaryResponse
 */
export type ProfileSummaryResponse = {
    /**
     * Topvarietals
     */
    topVarietals?: Array<string>;
    /**
     * Topregions
     */
    topRegions?: Array<string>;
    /**
     * Topproducers
     */
    topProducers?: Array<string>;
    /**
     * Highlyrated
     */
    highlyRated?: Array<{
        [key: string]: string;
    }>;
    /**
     * Preferreddescriptors
     */
    preferredDescriptors?: Array<string>;
    /**
     * Avoidedstyles
     */
    avoidedStyles?: Array<string>;
    /**
     * Avgspend
     */
    avgSpend?: number | null;
    /**
     * Stylesummary
     */
    styleSummary?: string | null;
    tasteMarkers?: TasteMarkers | null;
    cellarStats?: CellarStats | null;
    /**
     * Profilesource
     */
    profileSource?: string | null;
    /**
     * Inferenceconfidence
     */
    inferenceConfidence?: string | null;
    /**
     * Seedbottlecount
     */
    seedBottleCount?: number | null;
};

/**
 * ProfileUpdateRequest
 */
export type ProfileUpdateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Isdefault
     */
    isDefault?: boolean | null;
};

/**
 * RecommendationResponse
 */
export type RecommendationResponse = {
    /**
     * Recommendations
     */
    recommendations: Array<WineRecommendation>;
    /**
     * Listqualitynote
     */
    listQualityNote?: string | null;
    /**
     * Profilematchsummary
     */
    profileMatchSummary: string;
    /**
     * Flightid
     */
    flightId?: string | null;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * SeedBottle
 *
 * A single wine the user names during seed-bottle onboarding.
 */
export type SeedBottle = {
    /**
     * Producer
     */
    producer: string;
    /**
     * Wine
     */
    wine: string;
    /**
     * Vintage
     */
    vintage?: number | null;
    /**
     * Sentiment
     */
    sentiment?: 'loved' | 'disliked';
    /**
     * Note
     */
    note?: string | null;
};

/**
 * SeedProfileRequest
 *
 * Request body for POST /seed-profile.
 */
export type SeedProfileRequest = {
    /**
     * Loved
     */
    loved?: Array<SeedBottle>;
    /**
     * Disliked
     */
    disliked?: Array<SeedBottle>;
};

/**
 * StructureBars
 */
export type StructureBars = {
    /**
     * Tannin
     */
    tannin: number;
    /**
     * Acidity
     */
    acidity: number;
    /**
     * Body
     */
    body: number;
    /**
     * Sweetness
     */
    sweetness: number;
    /**
     * Oak
     */
    oak: number;
};

/**
 * TasteMarkers
 *
 * Heuristic taste-marker scores derived from preferred descriptors (1=very low … 5=very high).
 */
export type TasteMarkers = {
    /**
     * Acidity
     */
    acidity?: number;
    /**
     * Tannin
     */
    tannin?: number;
    /**
     * Body
     */
    body?: number;
    /**
     * Oak
     */
    oak?: number;
};

/**
 * TasteProfile
 *
 * Source-agnostic taste profile schema (quiz, CellarTracker, manual, etc.)
 */
export type TasteProfile = {
    /**
     * Preferredstyles
     */
    preferredStyles?: Array<string>;
    /**
     * Preferredregions
     */
    preferredRegions?: Array<string>;
    /**
     * Preferredgrapes
     */
    preferredGrapes?: Array<string>;
    /**
     * Avoidedstyles
     */
    avoidedStyles?: Array<string>;
    /**
     * Budgetmin
     */
    budgetMin?: number | null;
    /**
     * Budgetmax
     */
    budgetMax?: number | null;
    /**
     * Occasion
     */
    occasion?: string | null;
    /**
     * Foodpairing
     */
    foodPairing?: string | null;
    /**
     * Profilesource
     */
    profileSource?: string;
    /**
     * Inferenceconfidence
     */
    inferenceConfidence?: string | null;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Accesstoken
     */
    accessToken: string;
    /**
     * Tokentype
     */
    tokenType?: string;
    user: User;
    profile: Profile;
};

/**
 * UploadInventoryResponse
 */
export type UploadInventoryResponse = {
    /**
     * Count
     */
    count: number;
    /**
     * Message
     */
    message: string;
};

/**
 * UploadProfileResponse
 */
export type UploadProfileResponse = {
    /**
     * Exporttype
     */
    exportType: string;
    /**
     * Message
     */
    message: string;
    tasteProfile?: TasteProfile | null;
};

/**
 * User
 *
 * Public-facing user model. Password hash is never serialized.
 */
export type User = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Createdat
     */
    createdAt: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WineColor
 */
export type WineColor = {
    /**
     * Glass
     */
    glass: string;
    /**
     * Tint
     */
    tint: string;
    /**
     * Ink
     */
    ink: string;
    /**
     * Accent
     */
    accent: string;
};

/**
 * WineRecommendation
 */
export type WineRecommendation = {
    /**
     * Rank
     */
    rank: number;
    /**
     * Winename
     */
    wineName: string;
    /**
     * Producer
     */
    producer?: string | null;
    /**
     * Vintage
     */
    vintage?: number | null;
    /**
     * Region
     */
    region?: string | null;
    /**
     * Price
     */
    price?: number | null;
    /**
     * Reasoning
     */
    reasoning: string;
    /**
     * Confidence
     */
    confidence: string;
    /**
     * Fits
     */
    fits?: Array<string> | null;
    /**
     * Appellation
     */
    appellation?: string | null;
    /**
     * Country
     */
    country?: string | null;
    coords?: Coords | null;
    /**
     * Grape
     */
    grape?: string | null;
    /**
     * Abv
     */
    abv?: number | null;
    drink?: DrinkWindow | null;
    color?: WineColor | null;
    bars?: StructureBars | null;
    /**
     * Wheel
     */
    wheel?: {
        [key: string]: number;
    } | null;
    /**
     * Nose
     */
    nose?: string | null;
    /**
     * Palate
     */
    palate?: string | null;
    /**
     * Pairs
     */
    pairs?: Array<string> | null;
    critic?: Critic | null;
    /**
     * Verifiedonlist
     */
    verifiedOnList?: boolean | null;
};

export type RegisterAuthRegisterPostData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterAuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterAuthRegisterPostError = RegisterAuthRegisterPostErrors[keyof RegisterAuthRegisterPostErrors];

export type RegisterAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: TokenResponse;
};

export type RegisterAuthRegisterPostResponse = RegisterAuthRegisterPostResponses[keyof RegisterAuthRegisterPostResponses];

export type LoginAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type MeAuthMeGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type MeAuthMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeAuthMeGetError = MeAuthMeGetErrors[keyof MeAuthMeGetErrors];

export type MeAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: AuthMeResponse;
};

export type MeAuthMeGetResponse = MeAuthMeGetResponses[keyof MeAuthMeGetResponses];

export type ListProfilesProfilesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/profiles';
};

export type ListProfilesProfilesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProfilesProfilesGetError = ListProfilesProfilesGetErrors[keyof ListProfilesProfilesGetErrors];

export type ListProfilesProfilesGetResponses = {
    /**
     * Response List Profiles Profiles Get
     *
     * Successful Response
     */
    200: Array<Profile>;
};

export type ListProfilesProfilesGetResponse = ListProfilesProfilesGetResponses[keyof ListProfilesProfilesGetResponses];

export type CreateProfileProfilesPostData = {
    body: ProfileCreateRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/profiles';
};

export type CreateProfileProfilesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProfileProfilesPostError = CreateProfileProfilesPostErrors[keyof CreateProfileProfilesPostErrors];

export type CreateProfileProfilesPostResponses = {
    /**
     * Successful Response
     */
    201: Profile;
};

export type CreateProfileProfilesPostResponse = CreateProfileProfilesPostResponses[keyof CreateProfileProfilesPostResponses];

export type DeleteProfileProfilesProfileIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/profiles/{profile_id}';
};

export type DeleteProfileProfilesProfileIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProfileProfilesProfileIdDeleteError = DeleteProfileProfilesProfileIdDeleteErrors[keyof DeleteProfileProfilesProfileIdDeleteErrors];

export type DeleteProfileProfilesProfileIdDeleteResponses = {
    /**
     * Response Delete Profile Profiles  Profile Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteProfileProfilesProfileIdDeleteResponse = DeleteProfileProfilesProfileIdDeleteResponses[keyof DeleteProfileProfilesProfileIdDeleteResponses];

export type UpdateProfileProfilesProfileIdPatchData = {
    body: ProfileUpdateRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/profiles/{profile_id}';
};

export type UpdateProfileProfilesProfileIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProfileProfilesProfileIdPatchError = UpdateProfileProfilesProfileIdPatchErrors[keyof UpdateProfileProfilesProfileIdPatchErrors];

export type UpdateProfileProfilesProfileIdPatchResponses = {
    /**
     * Successful Response
     */
    200: Profile;
};

export type UpdateProfileProfilesProfileIdPatchResponse = UpdateProfileProfilesProfileIdPatchResponses[keyof UpdateProfileProfilesProfileIdPatchResponses];

export type HealthCheckDebugHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/health';
};

export type HealthCheckDebugHealthGetResponses = {
    /**
     * Response Health Check Debug Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthCheckDebugHealthGetResponse = HealthCheckDebugHealthGetResponses[keyof HealthCheckDebugHealthGetResponses];

export type StatusOverviewDebugStatusGetData = {
    body?: never;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/debug/status';
};

export type StatusOverviewDebugStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StatusOverviewDebugStatusGetError = StatusOverviewDebugStatusGetErrors[keyof StatusOverviewDebugStatusGetErrors];

export type StatusOverviewDebugStatusGetResponses = {
    /**
     * Response Status Overview Debug Status Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type StatusOverviewDebugStatusGetResponse = StatusOverviewDebugStatusGetResponses[keyof StatusOverviewDebugStatusGetResponses];

export type CacheStatsDebugCacheStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/cache/stats';
};

export type CacheStatsDebugCacheStatsGetResponses = {
    /**
     * Response Cache Stats Debug Cache Stats Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type CacheStatsDebugCacheStatsGetResponse = CacheStatsDebugCacheStatsGetResponses[keyof CacheStatsDebugCacheStatsGetResponses];

export type ClearCacheDebugCacheClearPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/debug/cache/clear';
};

export type ClearCacheDebugCacheClearPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ClearCacheDebugCacheClearPostError = ClearCacheDebugCacheClearPostErrors[keyof ClearCacheDebugCacheClearPostErrors];

export type ClearCacheDebugCacheClearPostResponses = {
    /**
     * Response Clear Cache Debug Cache Clear Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ClearCacheDebugCacheClearPostResponse = ClearCacheDebugCacheClearPostResponses[keyof ClearCacheDebugCacheClearPostResponses];

export type GetConfigDebugConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/config';
};

export type GetConfigDebugConfigGetResponses = {
    /**
     * Response Get Config Debug Config Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetConfigDebugConfigGetResponse = GetConfigDebugConfigGetResponses[keyof GetConfigDebugConfigGetResponses];

export type GetRecentLogsDebugLogsRecentGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/debug/logs/recent';
};

export type GetRecentLogsDebugLogsRecentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecentLogsDebugLogsRecentGetError = GetRecentLogsDebugLogsRecentGetErrors[keyof GetRecentLogsDebugLogsRecentGetErrors];

export type GetRecentLogsDebugLogsRecentGetResponses = {
    /**
     * Response Get Recent Logs Debug Logs Recent Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetRecentLogsDebugLogsRecentGetResponse = GetRecentLogsDebugLogsRecentGetResponses[keyof GetRecentLogsDebugLogsRecentGetResponses];

export type ListEndpointsDebugEndpointsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/endpoints';
};

export type ListEndpointsDebugEndpointsGetResponses = {
    /**
     * Response List Endpoints Debug Endpoints Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListEndpointsDebugEndpointsGetResponse = ListEndpointsDebugEndpointsGetResponses[keyof ListEndpointsDebugEndpointsGetResponses];

export type MemoryUsageDebugMemoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/memory';
};

export type MemoryUsageDebugMemoryGetResponses = {
    /**
     * Response Memory Usage Debug Memory Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type MemoryUsageDebugMemoryGetResponse = MemoryUsageDebugMemoryGetResponses[keyof MemoryUsageDebugMemoryGetResponses];

export type PingDebugPingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/ping';
};

export type PingDebugPingGetResponses = {
    /**
     * Response Ping Debug Ping Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type PingDebugPingGetResponse = PingDebugPingGetResponses[keyof PingDebugPingGetResponses];

export type GetVersionDebugVersionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/version';
};

export type GetVersionDebugVersionGetResponses = {
    /**
     * Response Get Version Debug Version Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetVersionDebugVersionGetResponse = GetVersionDebugVersionGetResponses[keyof GetVersionDebugVersionGetResponses];

export type ListHistoryHistoryGetData = {
    body?: never;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/history';
};

export type ListHistoryHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListHistoryHistoryGetError = ListHistoryHistoryGetErrors[keyof ListHistoryHistoryGetErrors];

export type ListHistoryHistoryGetResponses = {
    /**
     * Response List History History Get
     *
     * Successful Response
     */
    200: Array<FlightSummary>;
};

export type ListHistoryHistoryGetResponse = ListHistoryHistoryGetResponses[keyof ListHistoryHistoryGetResponses];

export type DeleteHistoryHistoryFlightIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Flight Id
         */
        flight_id: string;
    };
    query?: never;
    url: '/history/{flight_id}';
};

export type DeleteHistoryHistoryFlightIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteHistoryHistoryFlightIdDeleteError = DeleteHistoryHistoryFlightIdDeleteErrors[keyof DeleteHistoryHistoryFlightIdDeleteErrors];

export type DeleteHistoryHistoryFlightIdDeleteResponses = {
    /**
     * Response Delete History History  Flight Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteHistoryHistoryFlightIdDeleteResponse = DeleteHistoryHistoryFlightIdDeleteResponses[keyof DeleteHistoryHistoryFlightIdDeleteResponses];

export type GetHistoryHistoryFlightIdGetData = {
    body?: never;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Flight Id
         */
        flight_id: string;
    };
    query?: never;
    url: '/history/{flight_id}';
};

export type GetHistoryHistoryFlightIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHistoryHistoryFlightIdGetError = GetHistoryHistoryFlightIdGetErrors[keyof GetHistoryHistoryFlightIdGetErrors];

export type GetHistoryHistoryFlightIdGetResponses = {
    /**
     * Successful Response
     */
    200: FlightRecord;
};

export type GetHistoryHistoryFlightIdGetResponse = GetHistoryHistoryFlightIdGetResponses[keyof GetHistoryHistoryFlightIdGetResponses];

export type PatchFeedbackHistoryFlightIdFeedbackPatchData = {
    body: FlightFeedback;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Flight Id
         */
        flight_id: string;
    };
    query?: never;
    url: '/history/{flight_id}/feedback';
};

export type PatchFeedbackHistoryFlightIdFeedbackPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchFeedbackHistoryFlightIdFeedbackPatchError = PatchFeedbackHistoryFlightIdFeedbackPatchErrors[keyof PatchFeedbackHistoryFlightIdFeedbackPatchErrors];

export type PatchFeedbackHistoryFlightIdFeedbackPatchResponses = {
    /**
     * Response Patch Feedback History  Flight Id  Feedback Patch
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PatchFeedbackHistoryFlightIdFeedbackPatchResponse = PatchFeedbackHistoryFlightIdFeedbackPatchResponses[keyof PatchFeedbackHistoryFlightIdFeedbackPatchResponses];

export type UploadInventoryUploadInventoryPostData = {
    body: BodyUploadInventoryUploadInventoryPost;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/upload-inventory';
};

export type UploadInventoryUploadInventoryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadInventoryUploadInventoryPostError = UploadInventoryUploadInventoryPostErrors[keyof UploadInventoryUploadInventoryPostErrors];

export type UploadInventoryUploadInventoryPostResponses = {
    /**
     * Successful Response
     */
    200: UploadInventoryResponse;
};

export type UploadInventoryUploadInventoryPostResponse = UploadInventoryUploadInventoryPostResponses[keyof UploadInventoryUploadInventoryPostResponses];

export type GetInventoryInventoryGetData = {
    body?: never;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/inventory';
};

export type GetInventoryInventoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInventoryInventoryGetError = GetInventoryInventoryGetErrors[keyof GetInventoryInventoryGetErrors];

export type GetInventoryInventoryGetResponses = {
    /**
     * Successful Response
     */
    200: InventoryResponse;
};

export type GetInventoryInventoryGetResponse = GetInventoryInventoryGetResponses[keyof GetInventoryInventoryGetResponses];

export type UploadProfileUploadProfilePostData = {
    body: BodyUploadProfileUploadProfilePost;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/upload-profile';
};

export type UploadProfileUploadProfilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadProfileUploadProfilePostError = UploadProfileUploadProfilePostErrors[keyof UploadProfileUploadProfilePostErrors];

export type UploadProfileUploadProfilePostResponses = {
    /**
     * Successful Response
     */
    200: UploadProfileResponse;
};

export type UploadProfileUploadProfilePostResponse = UploadProfileUploadProfilePostResponses[keyof UploadProfileUploadProfilePostResponses];

export type SeedProfileSeedProfilePostData = {
    body: SeedProfileRequest;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/seed-profile';
};

export type SeedProfileSeedProfilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SeedProfileSeedProfilePostError = SeedProfileSeedProfilePostErrors[keyof SeedProfileSeedProfilePostErrors];

export type SeedProfileSeedProfilePostResponses = {
    /**
     * Successful Response
     */
    200: UploadProfileResponse;
};

export type SeedProfileSeedProfilePostResponse = SeedProfileSeedProfilePostResponses[keyof SeedProfileSeedProfilePostResponses];

export type RevertProfileProfileRevertPostData = {
    body?: never;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/profile/revert';
};

export type RevertProfileProfileRevertPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevertProfileProfileRevertPostError = RevertProfileProfileRevertPostErrors[keyof RevertProfileProfileRevertPostErrors];

export type RevertProfileProfileRevertPostResponses = {
    /**
     * Response Revert Profile Profile Revert Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type RevertProfileProfileRevertPostResponse = RevertProfileProfileRevertPostResponses[keyof RevertProfileProfileRevertPostResponses];

export type ProfileSummaryProfileSummaryGetData = {
    body?: never;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/profile-summary';
};

export type ProfileSummaryProfileSummaryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfileSummaryProfileSummaryGetError = ProfileSummaryProfileSummaryGetErrors[keyof ProfileSummaryProfileSummaryGetErrors];

export type ProfileSummaryProfileSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: ProfileSummaryResponse;
};

export type ProfileSummaryProfileSummaryGetResponse = ProfileSummaryProfileSummaryGetResponses[keyof ProfileSummaryProfileSummaryGetResponses];

export type PatchProfileProfilePatchData = {
    body: ProfilePatchRequest;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/profile';
};

export type PatchProfileProfilePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchProfileProfilePatchError = PatchProfileProfilePatchErrors[keyof PatchProfileProfilePatchErrors];

export type PatchProfileProfilePatchResponses = {
    /**
     * Successful Response
     */
    200: ProfileSummaryResponse;
};

export type PatchProfileProfilePatchResponse = PatchProfileProfilePatchResponses[keyof PatchProfileProfilePatchResponses];

export type RecommendRecommendPostData = {
    body?: BodyRecommendRecommendPost;
    headers?: {
        /**
         * X-Profile-Id
         */
        'X-Profile-Id'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/recommend';
};

export type RecommendRecommendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecommendRecommendPostError = RecommendRecommendPostErrors[keyof RecommendRecommendPostErrors];

export type RecommendRecommendPostResponses = {
    /**
     * Successful Response
     */
    200: RecommendationResponse;
};

export type RecommendRecommendPostResponse = RecommendRecommendPostResponses[keyof RecommendRecommendPostResponses];
