// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_recommend_recommend_post
 */
export type BodyRecommendRecommendPost = {
    /**
     * Wine List
     */
    wine_list: Blob | File;
    /**
     * Meal
     */
    meal: string;
    /**
     * Style Terms
     */
    style_terms?: string;
};

/**
 * Body_upload_inventory_upload_inventory_post
 */
export type BodyUploadInventoryUploadInventoryPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_profile_upload_profile_post
 */
export type BodyUploadProfileUploadProfilePost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Bottle
 *
 * Model for a wine bottle from CellarTracker
 */
export type Bottle = {
    /**
     * Iwine
     */
    iWine?: string | null;
    /**
     * Type
     */
    type?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Size
     */
    size?: string | null;
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Value
     */
    value?: string | null;
    /**
     * Price
     */
    price?: string | null;
    /**
     * Totalquantity
     */
    totalquantity?: string | null;
    /**
     * Quantity
     */
    quantity?: string | null;
    /**
     * Pending
     */
    pending?: string | null;
    /**
     * Vintage
     */
    vintage?: string | null;
    /**
     * Wine
     */
    wine?: string | null;
    /**
     * Locale
     */
    locale?: string | null;
    /**
     * Producer
     */
    producer?: string | null;
    /**
     * Varietal
     */
    varietal?: string | null;
    /**
     * Mastervarietal
     */
    mastervarietal?: string | null;
    /**
     * Designation
     */
    designation?: string | null;
    /**
     * Vineyard
     */
    vineyard?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Region
     */
    region?: string | null;
    /**
     * Subregion
     */
    subregion?: string | null;
    /**
     * Appellation
     */
    appellation?: string | null;
    /**
     * Beginconsume
     */
    beginconsume?: string | null;
    /**
     * Endconsume
     */
    endconsume?: string | null;
    /**
     * Windowsource
     */
    windowsource?: string | null;
    /**
     * Likevotes
     */
    likevotes?: string | null;
    /**
     * Likepercent
     */
    likepercent?: string | null;
    /**
     * Likeit
     */
    likeit?: string | null;
    /**
     * Pnotes
     */
    pnotes?: string | null;
    /**
     * Pscore
     */
    pscore?: string | null;
    /**
     * Cnotes
     */
    cnotes?: string | null;
    /**
     * Cscore
     */
    cscore?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InventoryResponse
 */
export type InventoryResponse = {
    /**
     * Bottles
     */
    bottles?: Array<Bottle>;
    /**
     * Agehours
     */
    ageHours?: number | null;
    /**
     * Stale
     */
    stale?: boolean;
};

/**
 * ProfileSummaryResponse
 */
export type ProfileSummaryResponse = {
    /**
     * Topvarietals
     */
    topVarietals?: Array<string>;
    /**
     * Topregions
     */
    topRegions?: Array<string>;
    /**
     * Topproducers
     */
    topProducers?: Array<string>;
    /**
     * Highlyrated
     */
    highlyRated?: Array<{
        [key: string]: string;
    }>;
    /**
     * Preferreddescriptors
     */
    preferredDescriptors?: Array<string>;
    /**
     * Avoidedstyles
     */
    avoidedStyles?: Array<string>;
    /**
     * Avgspend
     */
    avgSpend?: number | null;
};

/**
 * RecommendationResponse
 */
export type RecommendationResponse = {
    /**
     * Recommendations
     */
    recommendations: Array<WineRecommendation>;
    /**
     * Listqualitynote
     */
    listQualityNote?: string | null;
    /**
     * Profilematchsummary
     */
    profileMatchSummary: string;
};

/**
 * TasteProfile
 *
 * Source-agnostic taste profile schema (quiz, CellarTracker, manual, etc.)
 */
export type TasteProfile = {
    /**
     * Preferredstyles
     */
    preferredStyles?: Array<string>;
    /**
     * Preferredregions
     */
    preferredRegions?: Array<string>;
    /**
     * Preferredgrapes
     */
    preferredGrapes?: Array<string>;
    /**
     * Avoidedstyles
     */
    avoidedStyles?: Array<string>;
    /**
     * Budgetmin
     */
    budgetMin?: number | null;
    /**
     * Budgetmax
     */
    budgetMax?: number | null;
    /**
     * Occasion
     */
    occasion?: string | null;
    /**
     * Foodpairing
     */
    foodPairing?: string | null;
    /**
     * Profilesource
     */
    profileSource?: string;
};

/**
 * UploadInventoryResponse
 */
export type UploadInventoryResponse = {
    /**
     * Count
     */
    count: number;
    /**
     * Message
     */
    message: string;
};

/**
 * UploadProfileResponse
 */
export type UploadProfileResponse = {
    /**
     * Exporttype
     */
    exportType: string;
    /**
     * Message
     */
    message: string;
    tasteProfile?: TasteProfile | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WineRecommendation
 */
export type WineRecommendation = {
    /**
     * Rank
     */
    rank: number;
    /**
     * Winename
     */
    wineName: string;
    /**
     * Producer
     */
    producer?: string | null;
    /**
     * Vintage
     */
    vintage?: number | null;
    /**
     * Region
     */
    region?: string | null;
    /**
     * Price
     */
    price?: number | null;
    /**
     * Reasoning
     */
    reasoning: string;
    /**
     * Confidence
     */
    confidence: string;
};

export type HealthCheckDebugHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/health';
};

export type HealthCheckDebugHealthGetResponses = {
    /**
     * Response Health Check Debug Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthCheckDebugHealthGetResponse = HealthCheckDebugHealthGetResponses[keyof HealthCheckDebugHealthGetResponses];

export type StatusOverviewDebugStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/status';
};

export type StatusOverviewDebugStatusGetResponses = {
    /**
     * Response Status Overview Debug Status Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type StatusOverviewDebugStatusGetResponse = StatusOverviewDebugStatusGetResponses[keyof StatusOverviewDebugStatusGetResponses];

export type CacheStatsDebugCacheStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/cache/stats';
};

export type CacheStatsDebugCacheStatsGetResponses = {
    /**
     * Response Cache Stats Debug Cache Stats Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type CacheStatsDebugCacheStatsGetResponse = CacheStatsDebugCacheStatsGetResponses[keyof CacheStatsDebugCacheStatsGetResponses];

export type ClearCacheDebugCacheClearPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/cache/clear';
};

export type ClearCacheDebugCacheClearPostResponses = {
    /**
     * Response Clear Cache Debug Cache Clear Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ClearCacheDebugCacheClearPostResponse = ClearCacheDebugCacheClearPostResponses[keyof ClearCacheDebugCacheClearPostResponses];

export type GetConfigDebugConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/config';
};

export type GetConfigDebugConfigGetResponses = {
    /**
     * Response Get Config Debug Config Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetConfigDebugConfigGetResponse = GetConfigDebugConfigGetResponses[keyof GetConfigDebugConfigGetResponses];

export type GetRecentLogsDebugLogsRecentGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/debug/logs/recent';
};

export type GetRecentLogsDebugLogsRecentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecentLogsDebugLogsRecentGetError = GetRecentLogsDebugLogsRecentGetErrors[keyof GetRecentLogsDebugLogsRecentGetErrors];

export type GetRecentLogsDebugLogsRecentGetResponses = {
    /**
     * Response Get Recent Logs Debug Logs Recent Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetRecentLogsDebugLogsRecentGetResponse = GetRecentLogsDebugLogsRecentGetResponses[keyof GetRecentLogsDebugLogsRecentGetResponses];

export type ListEndpointsDebugEndpointsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/endpoints';
};

export type ListEndpointsDebugEndpointsGetResponses = {
    /**
     * Response List Endpoints Debug Endpoints Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListEndpointsDebugEndpointsGetResponse = ListEndpointsDebugEndpointsGetResponses[keyof ListEndpointsDebugEndpointsGetResponses];

export type MemoryUsageDebugMemoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/memory';
};

export type MemoryUsageDebugMemoryGetResponses = {
    /**
     * Response Memory Usage Debug Memory Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type MemoryUsageDebugMemoryGetResponse = MemoryUsageDebugMemoryGetResponses[keyof MemoryUsageDebugMemoryGetResponses];

export type PingDebugPingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/ping';
};

export type PingDebugPingGetResponses = {
    /**
     * Response Ping Debug Ping Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type PingDebugPingGetResponse = PingDebugPingGetResponses[keyof PingDebugPingGetResponses];

export type GetVersionDebugVersionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/version';
};

export type GetVersionDebugVersionGetResponses = {
    /**
     * Response Get Version Debug Version Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetVersionDebugVersionGetResponse = GetVersionDebugVersionGetResponses[keyof GetVersionDebugVersionGetResponses];

export type UploadInventoryUploadInventoryPostData = {
    body: BodyUploadInventoryUploadInventoryPost;
    path?: never;
    query?: never;
    url: '/upload-inventory';
};

export type UploadInventoryUploadInventoryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadInventoryUploadInventoryPostError = UploadInventoryUploadInventoryPostErrors[keyof UploadInventoryUploadInventoryPostErrors];

export type UploadInventoryUploadInventoryPostResponses = {
    /**
     * Successful Response
     */
    200: UploadInventoryResponse;
};

export type UploadInventoryUploadInventoryPostResponse = UploadInventoryUploadInventoryPostResponses[keyof UploadInventoryUploadInventoryPostResponses];

export type UploadProfileUploadProfilePostData = {
    body: BodyUploadProfileUploadProfilePost;
    path?: never;
    query?: never;
    url: '/upload-profile';
};

export type UploadProfileUploadProfilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadProfileUploadProfilePostError = UploadProfileUploadProfilePostErrors[keyof UploadProfileUploadProfilePostErrors];

export type UploadProfileUploadProfilePostResponses = {
    /**
     * Successful Response
     */
    200: UploadProfileResponse;
};

export type UploadProfileUploadProfilePostResponse = UploadProfileUploadProfilePostResponses[keyof UploadProfileUploadProfilePostResponses];

export type GetInventoryInventoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inventory';
};

export type GetInventoryInventoryGetResponses = {
    /**
     * Successful Response
     */
    200: InventoryResponse;
};

export type GetInventoryInventoryGetResponse = GetInventoryInventoryGetResponses[keyof GetInventoryInventoryGetResponses];

export type ProfileSummaryProfileSummaryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile-summary';
};

export type ProfileSummaryProfileSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: ProfileSummaryResponse;
};

export type ProfileSummaryProfileSummaryGetResponse = ProfileSummaryProfileSummaryGetResponses[keyof ProfileSummaryProfileSummaryGetResponses];

export type RecommendRecommendPostData = {
    body: BodyRecommendRecommendPost;
    path?: never;
    query?: never;
    url: '/recommend';
};

export type RecommendRecommendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecommendRecommendPostError = RecommendRecommendPostErrors[keyof RecommendRecommendPostErrors];

export type RecommendRecommendPostResponses = {
    /**
     * Successful Response
     */
    200: RecommendationResponse;
};

export type RecommendRecommendPostResponse = RecommendRecommendPostResponses[keyof RecommendRecommendPostResponses];
