// Wine data shared by both variations.
// Each wine has its actual color (used for per-card tinting),
// flavor wheel data, structural bars, and pairing context.

const WINES = [
  {
    id: 'brunello',
    rank: 1,
    name: 'Brunello di Montalcino',
    producer: 'Biondi-Santi',
    vintage: 2016,
    region: 'Tuscany',
    country: 'Italy',
    appellation: 'Montalcino · DOCG',
    coords: { lat: 43.05, lon: 11.49 }, // for relative positioning on Italy svg
    grape: 'Sangiovese (Brunello clone)',
    price: 185,
    abv: 14.5,
    drink: { from: 2024, peak: 2030, until: 2042 },
    // wine color — deep brick-garnet
    color: { glass: '#7d1f24', tint: '#f4dcd3', ink: '#3a0d10', accent: '#9a2a30' },
    confidence: 'high',
    confidenceNote: 'Strong style overlap with cellar favourites',
    bars: { tannin: 8, acidity: 7, body: 8, sweetness: 1, oak: 6 },
    wheel: {
      // each spoke 0-10; arranged radially
      'Dried Cherry': 9, 'Leather': 6, 'Tobacco': 5, 'Earth': 8,
      'Violet': 4, 'Plum': 6, 'Anise': 3, 'Forest Floor': 7,
    },
    nose: 'dried cherry · leather · tobacco · forest floor',
    palate: 'A structured Sangiovese that mirrors the savoury, dried-cherry profile your cellar leans on. The 2016 is drinking in its primary fruit window, matching the meal\'s richness without overshadowing it.',
    notes: [
      'Mirrors structured Sangiovese in your cellar',
      'Savoury earth & dried cherry you rate highly',
      'Decant 60 min before pour',
      'Serve at 17 °C from open bottle',
    ],
    fits: ['structured tannin', 'savoury earth', 'dried cherry', 'long finish'],
    pairs: ['Bistecca alla Fiorentina', 'Aged pecorino', 'Wild boar ragù'],
    critic: { score: 96, source: 'Galloni' },
  },
  {
    id: 'barolo',
    rank: 2,
    name: 'Barolo Cannubi',
    producer: 'Marchesi di Barolo',
    vintage: 2018,
    region: 'Piedmont',
    country: 'Italy',
    appellation: 'Barolo · DOCG',
    coords: { lat: 44.61, lon: 7.94 },
    grape: 'Nebbiolo',
    price: 145,
    abv: 14.0,
    drink: { from: 2025, peak: 2032, until: 2045 },
    // garnet with brick rim
    color: { glass: '#8a2a2e', tint: '#f3dad4', ink: '#3d1014', accent: '#a83339' },
    confidence: 'high',
    confidenceNote: 'Varietal and producer both align with profile',
    bars: { tannin: 9, acidity: 8, body: 7, sweetness: 1, oak: 5 },
    wheel: {
      'Rose Petal': 8, 'Tar': 7, 'Sour Cherry': 7, 'Truffle': 5,
      'Star Anise': 4, 'Raspberry': 5, 'Dried Herb': 6, 'Iron': 4,
    },
    nose: 'rose petal · tar · sour cherry · truffle',
    palate: 'Nebbiolo\'s rose-and-tar aromatics line up with the floral red wines you\'ve previously enjoyed. Younger and grippier than the Brunello — benefits from a decant before service.',
    notes: [
      'Floral red profile matches prior favourites',
      'Younger, grippier — decant 90 min',
      'Cannubi cru: pedigree producer',
      'Cellars to 2045',
    ],
    fits: ['floral nebbiolo', 'firm tannin', 'age-worthy', 'pedigree cru'],
    pairs: ['Brasato al Barolo', 'White truffle risotto', 'Aged comté'],
    critic: { score: 95, source: 'Suckling' },
  },
  {
    id: 'chablis',
    rank: 3,
    name: 'Chablis Grand Cru "Les Clos"',
    producer: 'Domaine William Fèvre',
    vintage: 2020,
    region: 'Burgundy',
    country: 'France',
    appellation: 'Chablis Grand Cru',
    coords: { lat: 47.81, lon: 3.80 },
    grape: 'Chardonnay',
    price: 135,
    abv: 13.0,
    drink: { from: 2024, peak: 2028, until: 2035 },
    // pale gold-straw
    color: { glass: '#d9b743', tint: '#f5ecc8', ink: '#5a4612', accent: '#b89826' },
    confidence: 'medium',
    confidenceNote: 'Adds contrast — mineral white to balance the reds',
    bars: { tannin: 1, acidity: 9, body: 6, sweetness: 1, oak: 3 },
    wheel: {
      'Lemon Zest': 8, 'Oyster Shell': 9, 'Green Apple': 7, 'Flint': 8,
      'White Flower': 5, 'Beeswax': 4, 'Almond': 4, 'Chalk': 8,
    },
    nose: 'lemon zest · oyster shell · flint · chalk',
    palate: 'A taut, chiselled Chablis with Kimmeridgian salinity. Les Clos has weight to stand up to richer dishes while keeping the cut you want from a great white Burgundy.',
    notes: [
      'Adds white-wine contrast to the flight',
      'Kimmeridgian minerality, low oak',
      'Serve 11 °C, no decant',
      'Drinking beautifully through 2030',
    ],
    fits: ['high acidity', 'mineral cut', 'restrained oak', 'grand cru pedigree'],
    pairs: ['Plateau de fruits de mer', 'Beurre blanc turbot', 'Comté affiné'],
    critic: { score: 94, source: 'Burghound' },
  },
];

window.WINES = WINES;
